arch: amd64

language: java

jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: test
      script: mvn clean test -B
    - stage: build
      script: mvn clean install -B