arch: amd64

language: java

jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

jobs:
  include:
    - stage: test
      script: ./mvnw clean test -B
    - stage: build
      script: ./mvnw clean install -B