arch: amd64

language: java

jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

install: skip

jobs:
  include:
    - stage: test
      script: ./mvnw clean test -B
    - stage: build
      script: ./mvnw clean install -B
    - stage: deploy to heroku
      script: skip
      before_deploy:
        - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: eat-it-users-app
        on:
          all_branches: true
        #  condition: $TRAVIS_BRANCH =~ ^(master|develop)$