eat-it:
  auth:
    url: https://eat-it-auth-app.herokuapp.com
  products:
    url: https://eat-it-products-app.herokuapp.com

spring:
  data:
    mongodb:
      database: usersDB
      uri: ${MONGO_URL}

server:
  port: ${PORT:8080}