eat-it:
  auth:
    url: https://eat-it-aut-app.osc-fr1.scalingo.io
  products:
    url: https://eat-it-products-app.osc-fr1.scalingo.io

spring:
  data:
    mongodb:
      database: usersDB
      uri: ${MONGO_URL}

server:
  port: ${PORT:8080}